interval: 10m
notify: email
smtp:
    host: smtp.gmail.com
    port: 587
    email: your-email@gmail.com
    password: your-password # If you use gmail, you need to generate an app password here: https://myaccount.google.com/apppasswords
