services:
- type: cron
  name: opencamp-cli
  runtime: go
  schedule: "0/10 * * * *"
  startCommand: ./build/opencamp-linux-amd64 check $CAMPGROUND_ID $START_DATE $END_DATE
  autoDeploy: false
  branch: main
  envVars:
    - key: CAMPGROUND_ID
      sync: false
      # value: "233116"
    - key: START_DATE
      sync: false
      # value: "09-11-2023"
    - key: END_DATE
      sync: false
      # value: "09-13-2023"
    - key: NOTIFY
      sync: false
      # value: "email"
    - key: SMTP_HOST
      sync: false
      # value: "smtp.gmail.com"
    - key: SMTP_PORT
      sync: false
      # value: "587"
    - key: SMTP_EMAIL
      sync: false
      # value: "your-email@gmail.com"
    - key: SMTP_PASSWORD
      sync: false
      # value: "your-password"
    - key: verbose
      sync: false
      # value: "true"
